Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 20

MixinUsage:
  Enabled: false

Documentation:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'spec/features/*.rb'
    - 'db/schema.rb'


UselessAssignment:
  Exclude:
    - 'spec/features/*.rb'

IfUnlessModifier:
    Exclude:
      - 'spec/rails_helper.rb'

IdenticalConditionalBranche:
    Enabled: false
